version: '3.7'

services:
  master:
    image: my-apache-spark:3.5.0.v1
    container_name: spark-docker-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8086:8080"
      - "7077:7077"
      - "4040:4040"
    networks:
      - spark-cluster-network
    volumes:
      - ./data:/data

  worker:
    image: my-apache-spark:3.5.0.v1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark-docker-master:7077
    networks:
      - spark-cluster-network
    deploy:
      replicas: 3

networks:
  spark-cluster-network:
    driver: bridge
